config/routes.rb
Rails.application.routes.draw do
  get "/flavors", to: "home#flavors", as: "flavors"
  get "/prices", to: "home#prices", as: "prices"
  get "/about", to: "home#about", as: "about"

  root 'home#show'
  devise_for :users, only: [:registrations, :sessions]

  authenticate :user do
    resources :simple_calendar
    resources :users
    resources :inventories  
    resources :photos, only: [:index, :new, :create]
    resources :products
    resources :shifts
    resources :schedules
    namespace :api do
      namespace :v1 do
        resources :users
      end
    end
    namespace :api do
      namespace :v1 do
        resources :posts
      end
    end
    namespace :api do
      namespace :v1 do
        resources :comments
      end
    end
    resources :inventories do
        get 'delete_all'
    end
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :amount, presence: true
  validates :number, presence: true
  validates :user_id, presence: true
  validates :product_id, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  def delete_all
    Inventory.where("created_at::date = ?", Inventory.where(id: params[:inventory_id])[0].created_at).destroy_all
    flash[:notice] = "You have removed all results!"
    redirect_to inventories_path
  end
  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show

  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    params[:inventory].each do |p|
      Inventory.create(amount: p[:amount].to_d, user_id: p[:user_id].to_i, product_id: p[:product_id].to_i, number: p[:number].to_i)
    end
    respond_to do |format|
      format.html { redirect_to inventories_path, notice: 'Inventory was successfully created.' }
      format.json { render :show, status: :created, location: @inventory }
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    params[:inventory].each do |p|
      Inventory.find(p[:inventory_id]).destroy
      Inventory.create(amount: p[:amount], user_id: p[:user_id].to_i, product_id: p[:product_id].to_i, number: p[:number].to_i)
    end
    respond_to do |format|
      format.html { redirect_to inventories_path, notice: 'Inventory was successfully updated.' }
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:amount, :user_id, :product_id, :number)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory, local: true) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row">
    <% Product.all.group_by{ |product| product.catagorie }.each do |catagorie, products| %>

      <div class="underline row">
        </br><h1><%= catagorie %></h1></br>
      </div>
      <div class="row">
        <% products.each do |product| %>

          <%= fields_for "inventory[]", inventory do |pf| %>

              <div class="float-left column small-4 column medium-2 columns large-1 columns">
                <%= pf.number_field :amount, class: :text_field, step: :any %>
              </div>
              <div class="float-left column small-8 columns column medium-4 large-3 columns">
                <h3><%= product.name %></h3>
                <%= pf.hidden_field :product_id, value: product.id %>
                <%= pf.hidden_field :user_id, value: current_user.id %>
                <%= pf.hidden_field :number, value:  1 %></br></br></br>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="row">
      <%= form.submit %>
    </div>


<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>
<%= form_with(model: @inventory, local: true, action: 'update_multiple') do |form| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% inventory = [] %>

  <% Inventory.where("created_at::date = ?", @inventory.created_at.to_date).each do |item| %>
    <%= fields_for "inventory[]", inventory do |pf| %>
      <%= item.product.name %>
      <%= pf.hidden_field :inventory_id, value: item.id %>
      <%= pf.hidden_field :product_id, value: item.product.id %>
      <%= pf.hidden_field :user_id, value: current_user.id %>
      <%= pf.hidden_field :number, value:  1 %>
      <div class="field">
        <%= pf.number_field :amount, class: :text_field, step: :any, value: item.amount %>
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<table>
  <thead>
    <tr>
      <th>Inventory</th>
    </tr>
  </thead>

  <tbody>

    <% @inventories.group_by{ |product| product.created_at.to_date }.each do |inventory| %>
      <tr>
        <td><%= link_to inventory[0].strftime("%m/%d/%y"), inventory_path(inventory[1][0].id)%></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Inventory ', new_inventory_path %>
 |<%= link_to 'Veiw Products', products_path %>

app/views/inventories/new.html.erb
<div class="row">
  <div class="underline large-6 large-centered columns">
  </br></br></br><h1>Inventory Form</h1></br>
  </div>
</div>
<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="float-left column small-12 column medium-6 columns large-6 columns">

    <strong><p>Inventory:</p></strong></br>

    <% Inventory.where("created_at::date = ?", @inventory.created_at.to_date).each do |product| %>
      <p>
        <%= product.amount %>
        <%= product.product.name %></br>
      </p>
    <% end %>
  </div>

  <div class="float-right column small-12 column medium-6 columns large-6 columns">

  <strong><p>Order:</p></strong></br>

  <% @inventory = Inventory.where("created_at::date = ?", @inventory.created_at.to_date) %>
  <% @inventory.each do |product| %>
    <p>
      <%= (product.product.amount_needed - product.amount).round %>
      <%= product.product.name %></br>
    </p>
  <% end %>

</div>

</div>

<div class="row">

  <%= link_to 'Edit', edit_inventory_path(@inventory[0]) %>
  | <%= link_to 'Back', inventories_path %>
  |
  <%= link_to "Delete", inventory_delete_all_path(@inventory[0]), :method => :get %>
</div>