config/routes.rb
Rails.application.routes.draw do
  get "/flavors", to: "home#flavors", as: "flavors"
  get "/prices", to: "home#prices", as: "prices"
  get "/about", to: "home#about", as: "about"

  root 'home#show'
  devise_for :users, only: [:registrations, :sessions]

  authenticate :user do
    resources :simple_calendar
    resources :users
    resources :inventories  
    resources :photos, only: [:index, :new, :create]
    resources :products
    resources :shifts
    resources :schedules
    namespace :api do
      namespace :v1 do
        resources :users
      end
    end
    namespace :api do
      namespace :v1 do
        resources :posts
      end
    end
    namespace :api do
      namespace :v1 do
        resources :comments
      end
    end
    resources :inventories do
        get 'delete_all'
    end
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twistee Treats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Comfortaa:400,700|Passion+One:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:400,500,700,800" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" />
    <script src="https://use.fontawesome.com/4401ab1d42.js"></script>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <div class="float-left cone">
            <%= image_tag "icecreamcone.png" %>
        </div>
        <div class="bold underline float-right menu-text"><%= link_to 'Twistee Treats', root_path %></div>
      </div>

      <div class="top-bar-right">
        <ul class="menu">
          <% if user_signed_in? %>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li><%= link_to 'Schedule', schedules_path %></li>
          <li><%= link_to 'Inventory', inventories_path %></li>
          <li><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %>
          </li>
          <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
          <% if flash[:notice] %>
          <div class="notice"><%= flash[:notice] %></div>
          <% elsif flash[:alert] %>
          <div class="alert"><%= flash[:alert] %></div>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="top-bar">
      <div class="large-12 large-centered columns">
        <ul class="submenu float-centered row large-12 large-centered columns">
          <li class="large-2 columns">&nbsp;</li>
          <li class="large-2 columns"><%= link_to 'Home', root_path %></li>
          <li class="large-2 columns"><%= link_to 'Prices', prices_path %></li>
          <li class="large-2 columns"><%= link_to 'Flavors', flavors_path %></li>
          <li class="large-2 columns"><%= link_to 'About', about_path %></li>
          <li class="large-2 columns"></li>
        </ul>
      </div>
    </div>
    <%= yield %>
  </body>
</html>